require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InternalCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # InternalCategory. As you add validations to InternalCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InternalCategoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all internal_categories as @internal_categories" do
      internal_category = InternalCategory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:internal_categories).should eq([internal_category])
    end
  end

  describe "GET show" do
    it "assigns the requested internal_category as @internal_category" do
      internal_category = InternalCategory.create! valid_attributes
      get :show, {:id => internal_category.to_param}, valid_session
      assigns(:internal_category).should eq(internal_category)
    end
  end

  describe "GET new" do
    it "assigns a new internal_category as @internal_category" do
      get :new, {}, valid_session
      assigns(:internal_category).should be_a_new(InternalCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested internal_category as @internal_category" do
      internal_category = InternalCategory.create! valid_attributes
      get :edit, {:id => internal_category.to_param}, valid_session
      assigns(:internal_category).should eq(internal_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InternalCategory" do
        expect {
          post :create, {:internal_category => valid_attributes}, valid_session
        }.to change(InternalCategory, :count).by(1)
      end

      it "assigns a newly created internal_category as @internal_category" do
        post :create, {:internal_category => valid_attributes}, valid_session
        assigns(:internal_category).should be_a(InternalCategory)
        assigns(:internal_category).should be_persisted
      end

      it "redirects to the created internal_category" do
        post :create, {:internal_category => valid_attributes}, valid_session
        response.should redirect_to(InternalCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved internal_category as @internal_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        InternalCategory.any_instance.stub(:save).and_return(false)
        post :create, {:internal_category => { "name" => "invalid value" }}, valid_session
        assigns(:internal_category).should be_a_new(InternalCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InternalCategory.any_instance.stub(:save).and_return(false)
        post :create, {:internal_category => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested internal_category" do
        internal_category = InternalCategory.create! valid_attributes
        # Assuming there are no other internal_categories in the database, this
        # specifies that the InternalCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InternalCategory.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => internal_category.to_param, :internal_category => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested internal_category as @internal_category" do
        internal_category = InternalCategory.create! valid_attributes
        put :update, {:id => internal_category.to_param, :internal_category => valid_attributes}, valid_session
        assigns(:internal_category).should eq(internal_category)
      end

      it "redirects to the internal_category" do
        internal_category = InternalCategory.create! valid_attributes
        put :update, {:id => internal_category.to_param, :internal_category => valid_attributes}, valid_session
        response.should redirect_to(internal_category)
      end
    end

    describe "with invalid params" do
      it "assigns the internal_category as @internal_category" do
        internal_category = InternalCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InternalCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => internal_category.to_param, :internal_category => { "name" => "invalid value" }}, valid_session
        assigns(:internal_category).should eq(internal_category)
      end

      it "re-renders the 'edit' template" do
        internal_category = InternalCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InternalCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => internal_category.to_param, :internal_category => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested internal_category" do
      internal_category = InternalCategory.create! valid_attributes
      expect {
        delete :destroy, {:id => internal_category.to_param}, valid_session
      }.to change(InternalCategory, :count).by(-1)
    end

    it "redirects to the internal_categories list" do
      internal_category = InternalCategory.create! valid_attributes
      delete :destroy, {:id => internal_category.to_param}, valid_session
      response.should redirect_to(internal_categories_url)
    end
  end

end
